stages:
  - deploy

deploy_dev:
  stage: deploy
  only:
    - dev-backend

  script:
    - ssh root@185.170.196.241 "
        cd /opt/karer/back-karer &&
        git fetch origin &&
        git reset --hard origin/dev-backend &&
        docker compose build &&
        docker compose up -d
      "