stages:
  - deploy

deploy_backend:
  stage: deploy
  tags:
    - docker
  only:
    - dev-backend

  script:
    - ssh root@185.170.196.241 "
        cd /opt/karer/back-karer &&
        git fetch origin &&
        git reset --hard origin/dev-backend &&
        docker compose build &&
        docker compose up -d
      "

  after_script:
    - ssh root@185.170.196.241 "
        cd /opt/karer/back-karer &&
        docker compose ps
      "