export const candidateSelect = {
    id: true,
    fullName: true,
    city: true,
    cityCanonical: true,
    summary: true,
    salaryMin: true,
    salaryMax: true,
    currency: true,
    remoteOk: true,
    willingToRelocate: true,
    totalExperienceYears: true,
    originalCvUrl: true,
    isActive: true,
    createdAt: true,
    user: {
        select: {
            id: true,
            email: true,
            role: true,
            status: true,
        },
    },
    cvUpload: {
        select: {
            id: true,
            userId: true,
            createdAt: true,
            status: true,
            originalUrl: true,
            mimeType: true,
            sizeBytes: true,
            extractedText: true,
            parsedJson: true,
            confidence: true,
            errorMessage: true,
            parsedAt: true,
            expiresAt: true,
            reviewedAt: true,
        },
    },
    skills: {
        select: {
            profileId: true,
            updatedAt: true,
            createdAt: true,
            skillId: true,
            level: true,
            years: true,
        },
    },
    applications: {
        select: {
            id: true,
            status: true,
            createdAt: true,
            updatedAt: true,
            candidateProfileId: true,
            jobId: true,
            coverLetterId: true,
        },
    },
    cvAnalyses: {
        select: {
            id: true,
            summary: true,
            createdAt: true,
            updatedAt: true,
            profileId: true,
            level: true,
            overallScore: true,
            details: true,
            evaluationPromptVersion: true,
            llmModel: true,
            tokensUsed: true,
            llmConfidence: true,
            rawLlmResponse: true,
            isCurrent: true,
        },
    },
} as const;